CREATE BIGFILE TABLESPACE "STX_IDX_SML" DATAFILE '+HOLLY_NOMIRROR' SIZE 2000M AUTOEXTEND ON NEXT 1M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE BIGFILE TABLESPACE "STX_IDX_MED" DATAFILE '+HOLLY_NOMIRROR' SIZE 300M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE BIGFILE TABLESPACE "STX_IDX_LGE" DATAFILE '+HOLLY_NOMIRROR' SIZE 8550M AUTOEXTEND ON NEXT 25M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
