CREATE BIGFILE TABLESPACE "STX_DATA_SML" DATAFILE '+HOLLY_NOMIRROR' SIZE 1048M AUTOEXTEND ON NEXT 1M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE BIGFILE TABLESPACE "STX_DATA_MED" DATAFILE '+HOLLY_NOMIRROR' SIZE 75M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE BIGFILE TABLESPACE "STX_DATA_LGE" DATAFILE '+HOLLY_NOMIRROR' SIZE 300M AUTOEXTEND ON NEXT 25M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE BIGFILE TABLESPACE "STX_DATA_XLA" DATAFILE '+HOLLY_NOMIRROR' SIZE 150M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE BIGFILE TABLESPACE "STX_DATA_XXL" DATAFILE '+HOLLY_NOMIRROR' SIZE 6100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
